swagger: '2.0'
info:
  version: '1.0'
  title: Product Service
  contact: {}
host: localhost:8001
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /products:
    get:
      summary: Ambil daftar produk berdasarkan user_id
      tags:
        - Product_Service
      operationId: getProducts
      deprecated: false
      parameters:
        - name: user_id
          in: query
          required: true
          type: integer
          format: int32
        - name: Content-Type
          in: header
          required: false
          type: string
          enum: [application/json]
        - name: Accept
          in: header
          required: true
          type: string
      responses:
        '200':
          description: Berhasil mengambil data produk
tags:
  - name: Product_Service
